#!/bin/bash
set -e

gh_owner=ElementsProject
gh_repo=elements

case $(uname -m) in
  armv7l) arch="arm";;
  x86_64) arch="x86_64";;
  *) echo "Architecture $ARCH not supported by the installation script"; exit 1;;
esac

latest_version=$(wget -qO- https://api.github.com/repos/$gh_owner/$gh_repo/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
build=$latest_version-$arch-$OSTYPE.tar.gz
#version=$(cut -d '-' -f2 <<< $latest_version)

wget -qO- https://github.com/$gh_owner/$gh_repo/releases/download/$latest_version/$build | tar -xvz -C /tmp

mv /tmp/$latest_version/bin/elementsd /usr/bin/elementsd
mv /tmp/$latest_version/bin/elements-cli /usr/bin/elements-cli
