#!/bin/bash
set -e

gh_owner=ElementsProject
gh_repo=elements

latest_version=$(wget -qO- https://api.github.com/repos/$gh_owner/$gh_repo/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
version=$(cut -d '-' -f2 <<< $latest_version)
build=liquid-$version-x86_64-linux-gnu.tar.gz

wget -qO- https://github.com/$gh_owner/$gh_repo/releases/download/$latest_version/$build | tar -xvz -C /tmp

mv /tmp/liquid-$version/bin/liquidd /usr/bin/liquidd
mv /tmp/liquid-$version/bin/liquid-cli /usr/bin/liquid-cli
mv /tmp/liquid-$version/bin/liquid-tx /usr/bin/liquid-tx
