#!/bin/bash
set -e

gh_owner=ElementsProject
gh_repo=elements

case $(uname -m) in
  armv7l) arch="arm";;
  x86_64) arch="x86_64";;
  *) echo "Architecture $ARCH not supported by the installation script"; exit 1;;
esac

#latest_version=$(wget -qO- https://api.github.com/repos/$gh_owner/$gh_repo/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
# This locks the version to 0.17 to prevent to download broken 0.18 
latest_version=elements-0.17.0.3
build=$latest_version-$arch-$OSTYPE.tar.gz

wget -qO- https://github.com/$gh_owner/$gh_repo/releases/download/$latest_version/$build | tar -xvz -C /tmp


mv /tmp/elements-0.17.0/bin/elementsd /
mv /tmp/elements-0.17.0/bin/elements-cli /
